# Generated by Django 3.0.5 on 2020-05-02 15:57

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturs',
            name='id',
            field=models.CharField(default=api.models.lam, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
